language: java

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - openjdk8
  - openjdk11
  - oraclejdk8

install:
  - mvn install -DskipTests -Dgpg.skip -Dmaven.javadoc.skip -B -V

script:
  - mvn test -B
  - ./gradlew build

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.m2
